name: "Setup-OS depending on a parameter"
description: "Setup-OS depending on a parameter"
inputs:
  os:
    description: "Select os among multiples"
    required: true

  python-version:
    description: "Version of python to use"
    required: true
    default: "3.9"

runs:
  using: "composite"
  steps:
    - name: "Setup Linux"
      if: ${{ input.os }} == 'ubuntu-latest'
      uses: ./.github/actions/setup-linux
      with: 
        python-version: ${{ inputs.python-version }}

    - name: "Setup MacOS"
      if: ${{ input.os }} == 'macOS-latest'
      uses: ./.github/actions/setup-macos
      with: 
        python-version: ${{ inputs.python-version }}

    - name: "Setup Windows"
      if: ${{ input.os }} == 'windows-latest'
      uses: ./.github/actions/setup-linux
      with: 
        python-version: ${{ inputs.python-version }}
