name: "Setup-OS depending on a parameter"
description: "Setup-OS depending on a parameter"
inputs:
  python-version:
    description: "Version of python to use"
    required: true
    default: "3.9"

runs:
  using: "composite"
  steps:
    - name: "Setup Linux"
      if: ${{ runner.os == 'Linux'}}
      uses: ./.github/actions/setup-linux
      with: 
        python-version: ${{ inputs.python-version }}

    - name: "Setup MacOS"
      if: ${{ runner.os == 'macOS'}}
      uses: ./.github/actions/setup-macos
      with: 
        python-version: ${{ inputs.python-version }}

    - name: "Setup Windows"
      if: ${{ runner.os == 'Windows'}}
      uses: ./.github/actions/setup-windows
      with: 
        python-version: ${{ inputs.python-version }}
