language: cpp

compiler:
  - gcc
  - clang

cache: apt

env:
  - BTYPE="-DCMAKE_BUILD_TYPE=Debug -DWITH_QGLVIEWER=true -DBUILD_TESTING=ON"
  - BTYPE="-DCMAKE_BUILD_TYPE=Debug -DWITH_CAIRO=true -DWITH_GMP=true -DBUILD_TESTING=ON -DWARNING_AS_ERROR=OFF"
  - BTYPE="-DCMAKE_BUILD_TYPE=Debug  -DWITH_MAGICK=true -DBUILD_TESTING=ON"
  - BTYPE="-DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON"
  - BTYPE="-DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON -DWARNING_AS_ERROR=ON"

before_script:
  - sudo apt-get -qq update
  - sudo apt-get -qq install libboost-program-options-dev libcairo2-dev libgraphicsmagick++1-dev libboost-system-dev libgmp-dev libqglviewer-qt4-dev libinsighttoolkit3-dev libgdcm2-dev

matrix:
  exclude:
    - compiler: gcc
      env: BTYPE="-DCMAKE_BUILD_TYPE=Debug  -DWITH_MAGICK=true -DBUILD_TESTING=ON"
    - compiler: gcc
      env: BTYPE="-DCMAKE_BUILD_TYPE=Debug -DWITH_QGLVIEWER=true -DBUILD_TESTING=ON"
    - compiler: gcc
      env: BTYPE="-DCMAKE_BUILD_TYPE=Debug -DWITH_CAIRO=true -DBUILD_TESTING=ON  -DWARNING_AS_ERROR=ON"
    - compiler: clang
      env: BTYPE="-DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON  -DWARNING_AS_ERROR=ON"


script:
  - cmake . $BTYPE
  - make DGtal
  - make DGtalIO
  - cd examples && make &&  cd ../tests &&  make &&  cd ..&&  make test
