language: cpp

compiler:
  - gcc
  - clang

env:
  - BTYPE="-DCMAKE_BUILD_TYPE=Debug -DWITH_QGLVIEWER=true -DWITH_GMP=true" 
  - BTYPE="-DCMAKE_BUILD_TYPE=Release" 

before_script:
  - sudo apt-get -qq install libboost-program-options-dev libcairo2-dev libgraphicsmagick++1-dev libboost-system-dev libgmp-dev libqglviewer-qt4-dev

script: 
  - cmake . $BTYPE
  - make

after_script: 
  - "make test"
