language: cpp

compiler:
  - gcc
  - clang

env:
  - BTYPE="-DCMAKE_BUILD_TYPE=Debug -DWITH_QGLVIEWER=true -DBUILD_TESTING=ON"
  - BTYPE="-DCMAKE_BUILD_TYPE=Debug -DWITH_CAIRO=true -DBUILD_TESTING=ON"
  - BTYPE="-DCMAKE_BUILD_TYPE=Debug -DWITH_CGAL=true -DWITH_EIGEN=true -DWITH_MAGICK=true -DWITH_GMP=true -DWITH_ITK=true -DBUILD_TESTING=ON"
  - BTYPE="-DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON"
  - BTYPE="-DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON"

before_script:
  - sudo apt-get -qq install libboost-program-options-dev libcairo2-dev libgraphicsmagick++1-dev libboost-system-dev libboost-thread-dev libgmp-dev libqglviewer-qt4-dev libinsighttoolkit3-dev libgdcm2-dev libeigen3-dev liblapack-dev libblas-dev libmpfr-dev

##CGAL specific
  - mkdir cgal && cd cgal
  - wget https://gforge.inria.fr/frs/download.php/32994/CGAL-4.3.tar.gz
  - tar zxvf CGAL-4.3.tar.gz && cd CGAL-4.3
  - cmake . -DWITH_Eigen3=true -DWITH_GMPXX=true -DWITH_LAPACK=true -DWITH_BLAS=true
  - make >! /dev/bull
  - sudo make install >! /dev/null
  - cd ..




matrix:
  exclude:
    - compiler: gcc
      env: BTYPE="-DCMAKE_BUILD_TYPE=Debug -DWITH_QGLVIEWER=true -DBUILD_TESTING=ON"
    - compiler: gcc
      env: BTYPE="-DCMAKE_BUILD_TYPE=Debug -DWITH_CAIRO=true -DBUILD_TESTING=ON"
    - compiler: clang
      env: BTYPE="-DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON"


script:
  - cmake . $BTYPE
  - make DGtal
  - make DGtalIO
  - cd examples
  - make
  - cd ../tests
  - make
  - cd ..
  - make

after_script:
  - "make test"
