language: cpp

compiler:
  - gcc
  - clang

env:
  - BTYPE="-DCMAKE_BUILD_TYPE=Debug -DWITH_QGLVIEWER=true -DBUILD_TESTING=ON"
  - BTYPE="-DCMAKE_BUILD_TYPE=Debug -DWITH_CAIRO=true -DBUILD_TESTING=ON"
  - BTYPE="-DCMAKE_BUILD_TYPE=Debug -DWITH_CGAL=true -DWITH_EIGEN=true -DWITH_MAGICK=true -DWITH_GMP=true -DWITH_ITK=true -DBUILD_TESTING=ON"
  - BTYPE="-DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON"
  - BTYPE="-DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON"
  
before_script:
  - sudo apt-get -qq install libcgal-dev  libeigen3-dev libboost-program-options-dev libcairo2-dev libgraphicsmagick++1-dev libboost-system-dev libgmp-dev libqglviewer-qt4-dev libinsighttoolkit3-dev libgdcm2-dev



matrix:
  exclude:
    - compiler: gcc
      env: BTYPE="-DCMAKE_BUILD_TYPE=Debug -DWITH_QGLVIEWER=true -DBUILD_TESTING=ON"
    - compiler: gcc
      env: BTYPE="-DCMAKE_BUILD_TYPE=Debug -DWITH_CAIRO=true -DBUILD_TESTING=ON"
    - compiler: clang
      env: BTYPE="-DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON"


script:
  - cmake . $BTYPE
  - make DGtal
  - make DGtalIO
  - cd examples
  - make
  - cd ../tests
  - make
  - cd ..
  - make

after_script:
  - "make test"
