language: cpp

compiler:
  - gcc
  - clang

cache: apt

notifications:
  slack: dgtal:FObxCZFoeQkkaRuktJD5uhnN

env:
  global:
   - 

  matrix:
  - BTYPE="-DCMAKE_BUILD_TYPE=Debug -DWITH_MAGICK=true -DWITH_GMP=true  -DBUILD_TESTING=ON  -DWARNING_AS_ERROR=ON -DWITH_COVERAGE=true"
  - BTYPE="-DCMAKE_BUILD_TYPE=Debug -DWITH_CAIRO=true -DWITH_QGLVIEWER=true -DBUILD_TESTING=ON -DWARNING_AS_ERROR=OFF"


before_install:
   - openssl aes-256-cbc -K $encrypted_73d1df012ee4_key -iv $encrypted_73d1df012ee4_iv -in .travis/dgtal_rsa.enc -out .travis/dgtal_rsa -d
   - chmod 600 .travis/dgtal_rsa
   
before_script:
  - sudo apt-get -qq update
  - sudo apt-get -qq install libboost-program-options-dev libcairo2-dev libgraphicsmagick++1-dev libboost-system-dev libgmp-dev libqglviewer-qt4-dev libinsighttoolkit3-dev libgdcm2-dev graphviz doxygen
  - gem install coveralls-lcov
  - sudo apt-get install -y lcov

script:
  - cmake . $BTYPE
  - make DGtal && make DGtalIO
  - cd examples && make -j 3 
  - cd ../tests &&  make &&  cd ..&& make test

after_script:
  - make lcov
  - coveralls-lcov --source-encoding=ISO-8859-1 coverage/stap.info


after_success:
  - make doc
  - ssh-add .travis/dgtal_rsa
  - rsync -azv --delete --delete-after html/ dgtal@liris.cnrs.fr:/home/dgtal/public_html/doc/nightly/
