name: Building and deploying the documentation

on: [push]

#on:
#  push:
#    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Set up
      run:  sudo apt-get install libboost-dev graphviz texlive doxygen

    - name: Building pages
      run: |
         mkdir build
         cd build
         cmake ..
         wget --no-check-certificate -O "${{runner.workspace}}/DGtal/build/DGtalTools-tagfile" http://dgtal.org/doc/tags/DGtalTools-tagfile;
         make doc > buildDoc.log

    - name: Checking doc
      run: |
          pwd
          cd build
          export BUILD_DIR=${{runner.workspace}}/DGtal/build
          export SRC_DIR=${{runner.workspace}}/DGtal/
          ../.travis/checkDoxygenDocumentation.sh && ../.travis/check_src_file_tag.sh

#    - name: Deploy to GitHub Pages
#      uses: JamesIves/github-pages-deploy-action@3.4.6
#      with:
#        # This is the branch you wish to deploy to, for example gh-pages or docs.
#        ACCESS_TOKEN: ${{ secrets.deploytoken }}
#        BRANCH: gh-pages
#        FOLDER: tmp
#        SINGLE_COMMIT: true
#        CLEAN: true
