name: CI (linux/macOS/windows), PR

on:
  push:
    branches: [ CIPython ]
  pull_request:
    branches: [ CIPython ]

jobs:
  build_sdists:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        BUILD_TYPE: [ Release ]
        python-version: ["3.9"]
        exclude:
          -  os: windows-latest
             BUILD_TYPE: Debug

    steps: 
      - uses: actions/checkout@v4
        with:
          # Note: at least (5 + 1) for the whitelist to work
          fetch-depth: 6
      
      - name: Setup OS 
        uses: ./.github/actions/setup-os
        with:
          python-version: ${{ matrix.python-version }}

      - name: Conan (Windows)
        if: ${{ runner.os == 'Windows'}}
        run:
          ls .
          conan install $DGTAL_PATH --build=missing -s:a compiler.cppstd=20

      - name: Building wheels (Windows)
        if: ${{ runner.os == 'Windows'}}
        uses: pypa/cibuildwheel@v2.22
        env: 
          CMAKE_ARGS: -DENABLE_CONAN:BOOL=ON -DCMAKE_TOOLCHAIN_FILE=\"conan_toolchain.cmake\"

      - name: Building wheels (linux / macOS)
        if: ${{ runner.os != 'Windows'}}
        uses: pypa/cibuildwheel@v2.22

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          path: wheelhouse/*.whl
          name: dist-${{ matrix.os }}