name: CI (linux/macOS/windows), PR

on:
  push:
    branches: [ CIPython ]
  pull_request:
    branches: [ CIPython ]

jobs:
  build_sdists:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        BUILD_TYPE: [ Release ]
        python-version: ["3.9"]
        exclude:
          -  os: windows-latest
             BUILD_TYPE: Debug

    steps: 
      - uses: actions/checkout@v4
        with:
          # Note: at least (5 + 1) for the whitelist to work
          fetch-depth: 6
      
      - name: Setup OS 
        uses: ./.github/actions/setup-os
        with:
          python-version: ${{ matrix.python-version }}

      - name: Conan (Windows)
        shell: bash
        if: ${{ runner.os == 'Windows'}}
        run:
          conan install $DGTAL_PATH --build=missing -s:a compiler.cppstd=20

      - name: Building wheels (Windows)
        if: ${{ runner.os == 'Windows'}}
        uses: pypa/cibuildwheel@v2.22
        env: 
          CMAKE_ARGS: -DENABLE_CONAN:BOOL=ON -DCMAKE_TOOLCHAIN_FILE=\"conan_toolchain.cmake\"

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==3.1.4

      - name: Building wheels (linux / macOS)
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl