name: CI (linux/macOS/windows), PR

on:
  push:
    branches: [ CIPython ]
  pull_request:
    branches: [ CIPython ]

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps: 
      - uses: actions/checkout@v4
        with:
          # Note: at least (5 + 1) for the whitelist to work
          fetch-depth: 6
      
      - name: Setup OS 
        uses: ./.github/actions/setup-os
        with:
          python-version: "3.11" # At least 3.11 for cibuildwheel 3.1.4
                                 # Note that the tool will build other python versions. 

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==3.1.4

      - name: Conan (Windows)
        shell: bash
        if: ${{ runner.os == 'Windows'}}
        run:
          conan install ${{ runner.workspace }} --build=missing -s:a compiler.cppstd=20

      - name: Building wheels (Windows)
        if: ${{ runner.os == 'Windows' }}
        env:
          CMAKE_ARGS: -DCMAKE_BUILD_TYPE:STRING=Release -DENABLE_CONAN:BOOL=ON -DCMAKE_TOOLCHAIN_FILE:STRING=\"conan_toolchain.cmake\"
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Building wheels (linux / macOS)
        if: ${{ runner.os != 'Windows' }}
        env:
          CMAKE_ARGS: -DCMAKE_BUILD_TYPE:STRING=Release
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
